context:
  name: lazydocker
  version: "0.24.2"
  author: jesseduffield

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/${{ author }}/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2a8421f7c72b0a08b50f95af0994cef8c21cc16173fef23011849e50831ae33c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - ${{ name }} --version

about:
  homepage: https://github.com/${{ author }}/${{ name }}
  repository: https://github.com/${{ author }}/${{ name }}
  documentation: https://github.com/${{ author }}/${{ name }}/tree/v${{ version }}/docs
  summary: "The lazier way to manage everything docker"
  description: |
    This tool simplifies and automates Docker resource management through an intuitive interface,
    allowing developers to focus on their core tasks rather than remembering complex Docker commands.
    It streamlines container lifecycle management, image building and optimization, and volume/network configuration with minimal effort required.
    The tool supports customization through configuration files, making it easy to standardize development environments across teams.
    With features like batch container operations and automation of common command sequences,
    it effectively reduces the complexity of Docker operations while maintaining full compatibility with Docker's ecosystem and CI/CD pipelines.
  license: MIT
  license_file:
    - LICENSE
    - license-files/

extra:
  recipe-maintainers:
    - eunos-1128
