conda_build_tool: rattler-build
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
build_platform:
  osx_arm64: osx_64
test: native_and_emulated
